# Generated by Django 3.1.2 on 2023-06-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230627_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('validacion', 'Validación'), ('preparacion', 'Preparación'), ('reparto', 'Reparto'), ('entregado', 'Entregado')], default='validacion', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='1', max_length=50, unique=True),
        ),
    ]
